language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-practice-aws *
  - mkdir -p deploy
  - mv springboot-practice-aws.zip deploy/springboot-practice-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-practice-build-store
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-practice-build-store
    key: springboot-practice-aws.zip
    bundle_type: zip
    application: springboot-practice
    deployment_group: springboot-practice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'dev.dyllis@gmail.com'
